import { 
  FileType, 
  FileText, 
  ScanLine, 
  Globe, 
  Code, 
  CheckCircle2,
  FileSpreadsheet,
  FileType2,
  Files,
  Minimize2,
  Lock,
  Stamp,
  PenTool,
  ArrowUpDown,
  FileSignature,
  Scissors,
  Wrench,
  Presentation,
  Image as ImageIcon,
  RotateCw,
  Unlock,
  EyeOff,
  Crop,
  Hash,
  Scan,
  GitCompare,
  FileArchive,
  ArrowRightLeft,
  FilePlus
} from 'lucide-react';
import { ToolID, ToolConfig, ToolCategory } from './types';

export const TOOLS: Record<ToolID, ToolConfig> = {
  // --- ORGANIZE PDF ---
  [ToolID.PDF_MERGE]: {
    id: ToolID.PDF_MERGE,
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document.',
    icon: Files,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.ORGANIZE_PDF,
  },
  [ToolID.PDF_SPLIT]: {
    id: ToolID.PDF_SPLIT,
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    icon: Scissors,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.ORGANIZE_PDF,
  },
  [ToolID.PDF_ORGANIZE]: {
    id: ToolID.PDF_ORGANIZE,
    title: 'Organize PDF',
    description: 'Sort pages, delete pages, or reorder your PDF file.',
    icon: ArrowUpDown,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.ORGANIZE_PDF,
  },
  [ToolID.PDF_SCAN]: {
    id: ToolID.PDF_SCAN,
    title: 'Scan to PDF',
    description: 'Capture document scans and save them as PDF.',
    icon: Scan,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.ORGANIZE_PDF,
  },

  // --- OPTIMIZE PDF ---
  [ToolID.PDF_COMPRESS]: {
    id: ToolID.PDF_COMPRESS,
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal quality.',
    icon: Minimize2,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.OPTIMIZE_PDF,
  },
  [ToolID.PDF_REPAIR]: {
    id: ToolID.PDF_REPAIR,
    title: 'Repair PDF',
    description: 'Recover data from a corrupt or damaged PDF file.',
    icon: Wrench,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.OPTIMIZE_PDF,
  },

  // --- CONVERT FROM PDF ---
  [ToolID.PDF_TO_WORD]: {
    id: ToolID.PDF_TO_WORD,
    title: 'PDF to Word',
    description: 'Convert PDF documents into editable Word/Doc format.',
    icon: FileType2,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },
  [ToolID.PDF_TO_EXCEL]: {
    id: ToolID.PDF_TO_EXCEL,
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets.',
    icon: FileSpreadsheet,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },
  [ToolID.PDF_TO_POWERPOINT]: {
    id: ToolID.PDF_TO_POWERPOINT,
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into editable PPT slideshows.',
    icon: Presentation,
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },
  [ToolID.PDF_TO_JPG]: {
    id: ToolID.PDF_TO_JPG,
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },
  [ToolID.PDF_TO_PNG]: {
    id: ToolID.PDF_TO_PNG,
    title: 'PDF to PNG',
    description: 'Convert PDFs to PNG or other image formats.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },
  [ToolID.PDF_TO_PDFA]: {
    id: ToolID.PDF_TO_PDFA,
    title: 'PDF to PDF/A',
    description: 'Transform your PDF to ISO-standardized PDF/A for archiving.',
    icon: FileArchive,
    color: 'text-amber-700',
    bgColor: 'bg-amber-100',
    category: ToolCategory.CONVERT_FROM_PDF,
  },

  // --- CONVERT TO PDF ---
  [ToolID.GENERIC_TO_PDF]: {
    id: ToolID.GENERIC_TO_PDF,
    title: 'Convert to PDF',
    description: 'Turn almost any file (Doc, Images, etc) into a PDF.',
    icon: FilePlus,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },
  [ToolID.WORD_TO_PDF]: {
    id: ToolID.WORD_TO_PDF,
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting to PDF.',
    icon: FileType2,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },
  [ToolID.POWERPOINT_TO_PDF]: {
    id: ToolID.POWERPOINT_TO_PDF,
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view as PDF.',
    icon: Presentation,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },
  [ToolID.EXCEL_TO_PDF]: {
    id: ToolID.EXCEL_TO_PDF,
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting to PDF.',
    icon: FileSpreadsheet,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },
  [ToolID.JPG_TO_PDF]: {
    id: ToolID.JPG_TO_PDF,
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    icon: ImageIcon,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },
  [ToolID.HTML_TO_PDF]: {
    id: ToolID.HTML_TO_PDF,
    title: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF.',
    icon: Globe,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.CONVERT_TO_PDF,
  },

  // --- EDIT PDF ---
  [ToolID.PDF_EDIT]: {
    id: ToolID.PDF_EDIT,
    title: 'Edit PDF',
    description: 'Add text, shapes, comments and highlights to your PDF.',
    icon: PenTool,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.EDIT_PDF,
  },
  [ToolID.PDF_ROTATE]: {
    id: ToolID.PDF_ROTATE,
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them.',
    icon: RotateCw,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.EDIT_PDF,
  },
  [ToolID.PDF_PAGE_NUMBERS]: {
    id: ToolID.PDF_PAGE_NUMBERS,
    title: 'Page Numbers',
    description: 'Add page numbers into PDFs with ease.',
    icon: Hash,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.EDIT_PDF,
  },
  [ToolID.PDF_WATERMARK]: {
    id: ToolID.PDF_WATERMARK,
    title: 'Watermark',
    description: 'Stamp text or images over your PDF pages.',
    icon: Stamp,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.EDIT_PDF,
  },
  [ToolID.PDF_CROP]: {
    id: ToolID.PDF_CROP,
    title: 'Crop PDF',
    description: 'Crop margins of PDF documents or select specific areas.',
    icon: Crop,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.EDIT_PDF,
  },

  // --- PDF SECURITY ---
  [ToolID.PDF_UNLOCK]: {
    id: ToolID.PDF_UNLOCK,
    title: 'Unlock PDF',
    description: 'Remove PDF password security to use your PDFs.',
    icon: Unlock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.SECURITY_PDF,
  },
  [ToolID.PDF_PROTECT]: {
    id: ToolID.PDF_PROTECT,
    title: 'Protect PDF',
    description: 'Encrypt your PDF files with a password.',
    icon: Lock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.SECURITY_PDF,
  },
  [ToolID.PDF_REDACT]: {
    id: ToolID.PDF_REDACT,
    title: 'Redact PDF',
    description: 'Permanently remove sensitive information from a PDF.',
    icon: EyeOff,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.SECURITY_PDF,
  },
  [ToolID.PDF_SIGN]: {
    id: ToolID.PDF_SIGN,
    title: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures.',
    icon: FileSignature,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.SECURITY_PDF,
  },
  [ToolID.PDF_COMPARE]: {
    id: ToolID.PDF_COMPARE,
    title: 'Compare PDF',
    description: 'Show a side-by-side comparison to spot changes.',
    icon: GitCompare,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.SECURITY_PDF,
  },

  // --- AI INTELLIGENCE ---
  [ToolID.MAGIC_SUMMARIZER]: {
    id: ToolID.MAGIC_SUMMARIZER,
    title: 'Magic Summarizer',
    description: 'Condense long articles and documents into concise summaries.',
    icon: FileText,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },
  [ToolID.SMART_OCR]: {
    id: ToolID.SMART_OCR,
    title: 'Smart OCR',
    description: 'Extract editable text from scanned documents and images.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },
  [ToolID.PDF_OCR]: {
    id: ToolID.PDF_OCR,
    title: 'OCR PDF',
    description: 'Make scanned PDFs searchable and selectable.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },
  [ToolID.UNIVERSAL_TRANSLATOR]: {
    id: ToolID.UNIVERSAL_TRANSLATOR,
    title: 'Universal Translator',
    description: 'Translate text accurately into any language.',
    icon: Globe,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },
  [ToolID.CODE_MORPH]: {
    id: ToolID.CODE_MORPH,
    title: 'Code Morph',
    description: 'Convert code snippets between programming languages.',
    icon: Code,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },
  [ToolID.GRAMMAR_POLISH]: {
    id: ToolID.GRAMMAR_POLISH,
    title: 'Grammar Polish',
    description: 'Fix grammar, spelling, and improve writing tone.',
    icon: CheckCircle2,
    color: 'text-rose-500',
    bgColor: 'bg-rose-100',
    category: ToolCategory.AI_INTELLIGENCE,
  },

  // --- IMAGE TOOLS ---
  [ToolID.IMAGE_CONVERTER]: {
    id: ToolID.IMAGE_CONVERTER,
    title: 'Image Converter',
    description: 'Convert images to JPG, PNG, or WEBP instantly.',
    icon: FileType,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
    category: ToolCategory.IMAGE_TOOLS,
  },
};

export const LANGUAGES = [
  "English", "Spanish", "French", "German", "Chinese (Simplified)", 
  "Japanese", "Korean", "Russian", "Portuguese", "Italian", "Dutch"
];

export const CODING_LANGUAGES = [
  "JavaScript", "TypeScript", "Python", "Java", "C++", "C#", "Go", "Rust", "Swift", "PHP"
];