import { 
  FileType, 
  FileText, 
  ScanLine, 
  Globe, 
  Code, 
  CheckCircle2,
  FileSpreadsheet,
  FileType2,
  Files,
  Minimize2,
  Lock,
  Stamp,
  PenTool,
  ArrowUpDown,
  FileSignature,
  Scissors,
  Wrench,
  Presentation,
  Image as ImageIcon,
  RotateCw,
  Unlock,
  EyeOff,
  Crop,
  Hash,
  Scan,
  GitCompare,
  FileArchive,
  ArrowRightLeft,
  FilePlus,
  MessageSquare,
  Mic,
  Database,
  FileJson,
  FileCode,
  Table,
  File
} from 'lucide-react';
import { ToolID, ToolConfig, ToolCategory } from './types';

export const TOOLS: Record<ToolID, ToolConfig> = {
  // --- AI INTELLIGENCE ---
  [ToolID.CHAT_WITH_DOC]: {
    id: ToolID.CHAT_WITH_DOC,
    title: 'Chat with Doc',
    description: 'Upload any document and ask questions to get instant answers.',
    icon: MessageSquare,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['chat with pdf', 'ask document questions', 'ai document analysis', 'summarize pdf chat']
  },
  [ToolID.MAGIC_SUMMARIZER]: {
    id: ToolID.MAGIC_SUMMARIZER,
    title: 'Magic Summarizer',
    description: 'Condense long articles and documents into concise summaries.',
    icon: FileText,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['summarize text', 'text summarizer', 'ai summary generator', 'shorten article']
  },
  [ToolID.SMART_OCR]: {
    id: ToolID.SMART_OCR,
    title: 'Smart OCR',
    description: 'Extract editable text from scanned documents and images.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['image to text', 'online ocr', 'extract text from image', 'scanned document to text']
  },
  [ToolID.UNIVERSAL_TRANSLATOR]: {
    id: ToolID.UNIVERSAL_TRANSLATOR,
    title: 'Universal Translator',
    description: 'Translate text accurately into any language.',
    icon: Globe,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['translate document', 'language translator', 'free text translator']
  },
  [ToolID.CODE_MORPH]: {
    id: ToolID.CODE_MORPH,
    title: 'Code Morph',
    description: 'Convert code snippets between programming languages.',
    icon: Code,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['code converter', 'convert python to javascript', 'code translator']
  },
  [ToolID.GRAMMAR_POLISH]: {
    id: ToolID.GRAMMAR_POLISH,
    title: 'Grammar Polish',
    description: 'Fix grammar, spelling, and improve writing tone.',
    icon: CheckCircle2,
    color: 'text-rose-500',
    bgColor: 'bg-rose-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['grammar checker', 'fix spelling', 'improve writing ai']
  },

  // --- PDF TOOLS (Merged Utilities & Converters) ---
  [ToolID.PDF_MERGE]: {
    id: ToolID.PDF_MERGE,
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document.',
    icon: Files,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['merge pdf', 'combine pdf files', 'pdf joiner', 'merge pdf online free']
  },
  [ToolID.PDF_SPLIT]: {
    id: ToolID.PDF_SPLIT,
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    icon: Scissors,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['split pdf', 'extract pdf pages', 'separate pdf pages']
  },
  [ToolID.PDF_COMPRESS]: {
    id: ToolID.PDF_COMPRESS,
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal quality.',
    icon: Minimize2,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'optimize pdf']
  },
  [ToolID.PDF_EDIT]: {
    id: ToolID.PDF_EDIT,
    title: 'Edit PDF',
    description: 'Add text, shapes, comments and highlights to your PDF.',
    icon: PenTool,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['edit pdf', 'pdf editor online', 'annotate pdf']
  },
  [ToolID.PDF_SIGN]: {
    id: ToolID.PDF_SIGN,
    title: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures.',
    icon: FileSignature,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['sign pdf', 'esignature', 'digital signature pdf']
  },
  [ToolID.PDF_ORGANIZE]: {
    id: ToolID.PDF_ORGANIZE,
    title: 'Organize PDF',
    description: 'Sort pages, delete pages, or reorder your PDF file.',
    icon: ArrowUpDown,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_SCAN]: {
    id: ToolID.PDF_SCAN,
    title: 'Scan to PDF',
    description: 'Capture document scans and save them as PDF.',
    icon: Scan,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['scan to pdf', 'mobile scanner', 'document scanner']
  },
  [ToolID.PDF_PROTECT]: {
    id: ToolID.PDF_PROTECT,
    title: 'Protect PDF',
    description: 'Encrypt your PDF files with a password.',
    icon: Lock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['password protect pdf', 'encrypt pdf', 'lock pdf']
  },
  [ToolID.PDF_UNLOCK]: {
    id: ToolID.PDF_UNLOCK,
    title: 'Unlock PDF',
    description: 'Remove PDF password security to use your PDFs.',
    icon: Unlock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['unlock pdf', 'remove pdf password', 'decrypt pdf']
  },
  [ToolID.PDF_ROTATE]: {
    id: ToolID.PDF_ROTATE,
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them.',
    icon: RotateCw,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_PAGE_NUMBERS]: {
    id: ToolID.PDF_PAGE_NUMBERS,
    title: 'Page Numbers',
    description: 'Add page numbers into PDFs with ease.',
    icon: Hash,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_WATERMARK]: {
    id: ToolID.PDF_WATERMARK,
    title: 'Watermark',
    description: 'Stamp text or images over your PDF pages.',
    icon: Stamp,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_CROP]: {
    id: ToolID.PDF_CROP,
    title: 'Crop PDF',
    description: 'Crop margins of PDF documents or select specific areas.',
    icon: Crop,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_REPAIR]: {
    id: ToolID.PDF_REPAIR,
    title: 'Repair PDF',
    description: 'Recover data from a corrupt or damaged PDF file.',
    icon: Wrench,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_REDACT]: {
    id: ToolID.PDF_REDACT,
    title: 'Redact PDF',
    description: 'Permanently remove sensitive information from a PDF.',
    icon: EyeOff,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_COMPARE]: {
    id: ToolID.PDF_COMPARE,
    title: 'Compare PDF',
    description: 'Show a side-by-side comparison to spot changes.',
    icon: GitCompare,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_TO_WORD]: {
    id: ToolID.PDF_TO_WORD,
    title: 'PDF to Word',
    description: 'Convert PDF documents into editable Word/Doc format.',
    icon: FileType2,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to word', 'convert pdf to docx', 'pdf to doc converter']
  },
  [ToolID.PDF_TO_EXCEL]: {
    id: ToolID.PDF_TO_EXCEL,
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets.',
    icon: FileSpreadsheet,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to excel', 'convert pdf to xlsx', 'extract table from pdf']
  },
  [ToolID.PDF_TO_POWERPOINT]: {
    id: ToolID.PDF_TO_POWERPOINT,
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into editable PPT slideshows.',
    icon: Presentation,
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to ppt', 'convert pdf to powerpoint']
  },
  [ToolID.PDF_OCR]: {
    id: ToolID.PDF_OCR,
    title: 'OCR PDF',
    description: 'Make scanned PDFs searchable and selectable.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['ocr pdf', 'make pdf searchable', 'recognize text in pdf']
  },
  [ToolID.GENERIC_TO_PDF]: {
    id: ToolID.GENERIC_TO_PDF,
    title: 'Convert to PDF',
    description: 'Turn almost any file (Doc, Images, etc) into a PDF.',
    icon: FilePlus,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['convert to pdf', 'file to pdf', 'create pdf']
  },
  [ToolID.WORD_TO_PDF]: {
    id: ToolID.WORD_TO_PDF,
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting to PDF.',
    icon: FileType2,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['word to pdf', 'docx to pdf']
  },
  [ToolID.POWERPOINT_TO_PDF]: {
    id: ToolID.POWERPOINT_TO_PDF,
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view as PDF.',
    icon: Presentation,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['ppt to pdf', 'powerpoint to pdf']
  },
  [ToolID.EXCEL_TO_PDF]: {
    id: ToolID.EXCEL_TO_PDF,
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting to PDF.',
    icon: FileSpreadsheet,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['excel to pdf', 'xls to pdf']
  },
  [ToolID.JPG_TO_PDF]: {
    id: ToolID.JPG_TO_PDF,
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    icon: ImageIcon,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['jpg to pdf', 'image to pdf', 'convert photo to pdf']
  },
  [ToolID.HTML_TO_PDF]: {
    id: ToolID.HTML_TO_PDF,
    title: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF.',
    icon: Globe,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['html to pdf', 'webpage to pdf', 'url to pdf']
  },
  [ToolID.PDF_TO_JPG]: {
    id: ToolID.PDF_TO_JPG,
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to jpg', 'pdf to image']
  },
  [ToolID.PDF_TO_PNG]: {
    id: ToolID.PDF_TO_PNG,
    title: 'PDF to PNG',
    description: 'Convert PDFs to PNG or other image formats.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_TO_PDFA]: {
    id: ToolID.PDF_TO_PDFA,
    title: 'PDF to PDF/A',
    description: 'Transform your PDF to ISO-standardized PDF/A for archiving.',
    icon: FileArchive,
    color: 'text-amber-700',
    bgColor: 'bg-amber-100',
    category: ToolCategory.PDF_TOOLS,
  },

  // --- OFFICE TOOLS ---
  [ToolID.WORD_TO_EXCEL]: {
    id: ToolID.WORD_TO_EXCEL,
    title: 'Word to Excel',
    description: 'Convert data tables from Word documents to Excel sheets.',
    icon: FileSpreadsheet,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_WORD]: {
    id: ToolID.EXCEL_TO_WORD,
    title: 'Excel to Word',
    description: 'Convert spreadsheets into formatted Word documents.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.PPT_TO_WORD]: {
    id: ToolID.PPT_TO_WORD,
    title: 'PPT to Word',
    description: 'Convert PowerPoint slides into a Word document.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_PPT]: {
    id: ToolID.WORD_TO_PPT,
    title: 'Word to PowerPoint',
    description: 'Convert Word documents into a PowerPoint presentation.',
    icon: Presentation,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_CSV]: {
    id: ToolID.EXCEL_TO_CSV,
    title: 'Excel to CSV',
    description: 'Convert Excel spreadsheets to CSV format.',
    icon: FileSpreadsheet,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.CSV_TO_EXCEL]: {
    id: ToolID.CSV_TO_EXCEL,
    title: 'CSV to Excel',
    description: 'Convert CSV files into Excel spreadsheets.',
    icon: Table,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.TEXT_TO_WORD]: {
    id: ToolID.TEXT_TO_WORD,
    title: 'Text to Word',
    description: 'Convert plain text files into Word documents.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_TEXT]: {
    id: ToolID.WORD_TO_TEXT,
    title: 'Word to Text',
    description: 'Extract plain text from Word documents.',
    icon: FileText,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_JPG]: {
    id: ToolID.WORD_TO_JPG,
    title: 'Word to JPG',
    description: 'Convert Word document pages into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.PPT_TO_JPG]: {
    id: ToolID.PPT_TO_JPG,
    title: 'PPT to JPG',
    description: 'Convert PowerPoint slides into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_JPG]: {
    id: ToolID.EXCEL_TO_JPG,
    title: 'Excel to JPG',
    description: 'Convert Excel spreadsheets into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.MERGE_WORD]: {
    id: ToolID.MERGE_WORD,
    title: 'Merge Word',
    description: 'Combine multiple Word documents into one.',
    icon: Files,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['merge word documents', 'combine docx']
  },
  [ToolID.COMPRESS_WORD]: {
    id: ToolID.COMPRESS_WORD,
    title: 'Compress Word',
    description: 'Reduce the file size of Word documents.',
    icon: Minimize2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress word', 'reduce docx size', 'shrink word document']
  },
  [ToolID.COMPRESS_EXCEL]: {
    id: ToolID.COMPRESS_EXCEL,
    title: 'Compress Excel',
    description: 'Reduce the file size of Excel spreadsheets.',
    icon: Minimize2,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress excel', 'reduce xlsx size', 'shrink excel file']
  },
  [ToolID.COMPRESS_PPT]: {
    id: ToolID.COMPRESS_PPT,
    title: 'Compress PowerPoint',
    description: 'Reduce the file size of PowerPoint presentations.',
    icon: Minimize2,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress powerpoint', 'reduce ppt size', 'shrink presentation']
  },

  // --- DEVELOPER TOOLS ---
  [ToolID.JSON_TO_CSV]: {
    id: ToolID.JSON_TO_CSV,
    title: 'JSON to CSV',
    description: 'Convert JSON data structures to CSV format.',
    icon: Database,
    color: 'text-cyan-700',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['json to csv', 'convert json']
  },
  [ToolID.CSV_TO_JSON]: {
    id: ToolID.CSV_TO_JSON,
    title: 'CSV to JSON',
    description: 'Convert CSV spreadsheet data into JSON.',
    icon: FileJson,
    color: 'text-cyan-700',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },
  [ToolID.XML_TO_JSON]: {
    id: ToolID.XML_TO_JSON,
    title: 'XML to JSON',
    description: 'Convert XML data to JSON objects.',
    icon: FileCode,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },
  [ToolID.JSON_TO_XML]: {
    id: ToolID.JSON_TO_XML,
    title: 'JSON to XML',
    description: 'Convert JSON objects to XML format.',
    icon: FileCode,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },

  // --- IMAGE & AUDIO ---
  [ToolID.TEXT_TO_SPEECH]: {
    id: ToolID.TEXT_TO_SPEECH,
    title: 'Text to Speech',
    description: 'Convert written text into natural-sounding speech.',
    icon: Mic,
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['text to speech', 'free tts', 'read text aloud']
  },
  [ToolID.IMAGE_CONVERTER]: {
    id: ToolID.IMAGE_CONVERTER,
    title: 'Image Converter',
    description: 'Convert images to JPG, PNG, or WEBP instantly.',
    icon: FileType,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['image converter', 'jpg to png', 'png to jpg', 'webp converter']
  },
};

export const LANGUAGES = [
  "English", "Spanish", "French", "German", "Chinese (Simplified)", 
  "Japanese", "Korean", "Russian", "Portuguese", "Italian", "Dutch"
];

export const CODING_LANGUAGES = [
  "JavaScript", "TypeScript", "Python", "Java", "C++", "C#", "Go", "Rust", "Swift", "PHP"
];