import {
  FileType,
  FileText,
  ScanLine,
  Globe,
  Code,
  CheckCircle2,
  FileSpreadsheet,
  FileType2,
  Files,
  Minimize2,
  Lock,
  Stamp,
  PenTool,
  ArrowUpDown,
  FileSignature,
  Scissors,
  Wrench,
  Presentation,
  Image as ImageIcon,
  RotateCw,
  Unlock,
  EyeOff,
  Crop,
  Hash,
  Scan,
  GitCompare,
  Link,
  FileArchive,
  FilePlus,
  MessageSquare,
  Mic,
  Database,
  FileJson,
  FileCode,
  Table,
  Key as KeyIcon,
  Radio,
  Landmark,
  Tag,
  Monitor,
  Activity,
  QrCode,
  Search,
  ArrowRightLeft,
  Eraser,
  Type,
  Shield,
  AlignLeft,
  Calendar,
  Clock,
  Minus,
  Plus,
  Maximize,
  Palette,
  RefreshCw,
} from 'lucide-react';
import { ToolID, ToolConfig, ToolCategory } from './types';
import { TOOL_SEO_ENHANCEMENTS } from './seo-constants';

export const TOOLS: Record<ToolID, ToolConfig> = {
  // --- AI INTELLIGENCE ---
  [ToolID.CHAT_WITH_DOC]: {
    id: ToolID.CHAT_WITH_DOC,
    title: 'Chat with Doc',
    description: 'Upload any document and ask questions to get instant answers.',
    icon: MessageSquare,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.AI_TOOLS,
    keywords: [
      'chat with pdf',
      'ask document questions',
      'ai document analysis',
      'summarize pdf chat',
    ],
    seoTitle: 'Chat with PDF Documents - AI Document Assistant | All Things Doc',
    seoDescription:
      'Upload any PDF document and chat with AI to get instant answers, summaries, and insights. Free online document Q&A tool with no signup required.',
    longDescription:
      'Transform your document reading experience with our AI-powered chat tool. Upload PDFs, Word documents, or text files and ask questions in natural language. Get instant summaries, extract key information, and understand complex documents faster than ever.',
  },
  [ToolID.MAGIC_SUMMARIZER]: {
    id: ToolID.MAGIC_SUMMARIZER,
    title: 'Magic Summarizer',
    description: 'Condense long articles and documents into concise summaries.',
    icon: FileText,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['summarize text', 'text summarizer', 'ai summary generator', 'shorten article'],
    seoTitle: 'AI Text Summarizer - Summarize Documents & Articles Free | All Things Doc',
    seoDescription:
      'Summarize long documents, articles, and text instantly with AI. Free online text summarization tool that creates concise summaries while preserving key information.',
    longDescription:
      'Our AI Magic Summarizer uses advanced natural language processing to condense lengthy documents into clear, concise summaries. Perfect for students, researchers, and professionals who need to quickly understand large amounts of text.',
  },
  [ToolID.SMART_OCR]: {
    id: ToolID.SMART_OCR,
    title: 'Smart OCR',
    description: 'Extract editable text from scanned documents and images.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.AI_TOOLS,
    keywords: [
      'image to text',
      'online ocr',
      'extract text from image',
      'scanned document to text',
    ],
    seoTitle: 'Free Online OCR - Extract Text from Images & PDFs | All Things Doc',
    seoDescription:
      'Convert images and scanned documents to editable text with our free online OCR tool. Extract text from JPG, PNG, PDF files with high accuracy.',
    longDescription:
      'Transform scanned documents, photos, and images into editable text with our advanced OCR technology. Support for multiple languages and various image formats including JPG, PNG, and PDF. Perfect for digitizing printed documents.',
  },
  [ToolID.UNIVERSAL_TRANSLATOR]: {
    id: ToolID.UNIVERSAL_TRANSLATOR,
    title: 'Universal Translator',
    description: 'Translate text accurately into any language.',
    icon: Globe,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['translate document', 'language translator', 'free text translator'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.UNIVERSAL_TRANSLATOR].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.UNIVERSAL_TRANSLATOR].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.UNIVERSAL_TRANSLATOR].longDescription,
  },
  [ToolID.CODE_MORPH]: {
    id: ToolID.CODE_MORPH,
    title: 'Code Morph',
    description: 'Convert code snippets between programming languages.',
    icon: Code,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['code converter', 'convert python to javascript', 'code translator'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.CODE_MORPH].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.CODE_MORPH].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.CODE_MORPH].longDescription,
  },
  [ToolID.GRAMMAR_POLISH]: {
    id: ToolID.GRAMMAR_POLISH,
    title: 'Grammar Polish',
    description: 'Fix grammar, spelling, and improve writing tone.',
    icon: CheckCircle2,
    color: 'text-rose-500',
    bgColor: 'bg-rose-100',
    category: ToolCategory.AI_TOOLS,
    keywords: ['grammar checker', 'fix spelling', 'improve writing ai'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.GRAMMAR_POLISH].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.GRAMMAR_POLISH].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.GRAMMAR_POLISH].longDescription,
  },

  // --- PDF TOOLS (Merged Utilities & Converters) ---
  [ToolID.PDF_MERGE]: {
    id: ToolID.PDF_MERGE,
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document.',
    icon: Files,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['merge pdf', 'combine pdf files', 'pdf joiner', 'merge pdf online free'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_MERGE].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_MERGE].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_MERGE].longDescription,
  },
  [ToolID.PDF_SPLIT]: {
    id: ToolID.PDF_SPLIT,
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    icon: Scissors,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['split pdf', 'extract pdf pages', 'separate pdf pages'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_SPLIT].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_SPLIT].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_SPLIT].longDescription,
  },
  [ToolID.PDF_COMPRESS]: {
    id: ToolID.PDF_COMPRESS,
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal quality.',
    icon: Minimize2,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'optimize pdf'],
    seoTitle: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_COMPRESS].seoTitle,
    seoDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_COMPRESS].seoDescription,
    longDescription: TOOL_SEO_ENHANCEMENTS[ToolID.PDF_COMPRESS].longDescription,
  },
  [ToolID.PDF_EDIT]: {
    id: ToolID.PDF_EDIT,
    title: 'Edit PDF',
    description: 'Add text, shapes, comments and highlights to your PDF.',
    icon: PenTool,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['edit pdf', 'pdf editor online', 'annotate pdf'],
  },
  [ToolID.PDF_SIGN]: {
    id: ToolID.PDF_SIGN,
    title: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures.',
    icon: FileSignature,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['sign pdf', 'esignature', 'digital signature pdf'],
  },
  [ToolID.PDF_ORGANIZE]: {
    id: ToolID.PDF_ORGANIZE,
    title: 'Organize PDF',
    description: 'Sort pages, delete pages, or reorder your PDF file.',
    icon: ArrowUpDown,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_SCAN]: {
    id: ToolID.PDF_SCAN,
    title: 'Scan to PDF',
    description: 'Capture document scans and save them as PDF.',
    icon: Scan,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['scan to pdf', 'mobile scanner', 'document scanner'],
  },
  [ToolID.PDF_PROTECT]: {
    id: ToolID.PDF_PROTECT,
    title: 'Protect PDF',
    description: 'Encrypt your PDF files with a password.',
    icon: Lock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['password protect pdf', 'encrypt pdf', 'lock pdf'],
  },
  [ToolID.PDF_UNLOCK]: {
    id: ToolID.PDF_UNLOCK,
    title: 'Unlock PDF',
    description: 'Remove PDF password security to use your PDFs.',
    icon: Unlock,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['unlock pdf', 'remove pdf password', 'decrypt pdf'],
  },
  [ToolID.PDF_ROTATE]: {
    id: ToolID.PDF_ROTATE,
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them.',
    icon: RotateCw,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_PAGE_NUMBERS]: {
    id: ToolID.PDF_PAGE_NUMBERS,
    title: 'Page Numbers',
    description: 'Add page numbers into PDFs with ease.',
    icon: Hash,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_WATERMARK]: {
    id: ToolID.PDF_WATERMARK,
    title: 'Watermark',
    description: 'Stamp text or images over your PDF pages.',
    icon: Stamp,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_CROP]: {
    id: ToolID.PDF_CROP,
    title: 'Crop PDF',
    description: 'Crop margins of PDF documents or select specific areas.',
    icon: Crop,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_REPAIR]: {
    id: ToolID.PDF_REPAIR,
    title: 'Repair PDF',
    description: 'Recover data from a corrupt or damaged PDF file.',
    icon: Wrench,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_REDACT]: {
    id: ToolID.PDF_REDACT,
    title: 'Redact PDF',
    description: 'Permanently remove sensitive information from a PDF.',
    icon: EyeOff,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_COMPARE]: {
    id: ToolID.PDF_COMPARE,
    title: 'Compare PDF',
    description: 'Show a side-by-side comparison to spot changes.',
    icon: GitCompare,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_TO_WORD]: {
    id: ToolID.PDF_TO_WORD,
    title: 'PDF to Word',
    description: 'Convert PDF documents into editable Word/Doc format.',
    icon: FileType2,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to word', 'convert pdf to docx', 'pdf to doc converter'],
  },
  [ToolID.PDF_TO_EXCEL]: {
    id: ToolID.PDF_TO_EXCEL,
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets.',
    icon: FileSpreadsheet,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to excel', 'convert pdf to xlsx', 'extract table from pdf'],
  },
  [ToolID.PDF_TO_POWERPOINT]: {
    id: ToolID.PDF_TO_POWERPOINT,
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into editable PPT slideshows.',
    icon: Presentation,
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to ppt', 'convert pdf to powerpoint'],
  },
  [ToolID.PDF_OCR]: {
    id: ToolID.PDF_OCR,
    title: 'OCR PDF',
    description: 'Make scanned PDFs searchable and selectable.',
    icon: ScanLine,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['ocr pdf', 'make pdf searchable', 'recognize text in pdf'],
  },
  [ToolID.PDF_BANK_STATEMENT_CONVERTER]: {
    id: ToolID.PDF_BANK_STATEMENT_CONVERTER,
    title: 'Bank Statement Converter',
    description: 'AI-powered PDF bank statement to Excel/CSV converter. No login required.',
    icon: FileSpreadsheet,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: [
      'bank statement converter',
      'pdf to excel bank statement',
      'convert bank statement to csv',
      'ai bank statement extraction',
    ],
    seoTitle: 'AI PDF Bank Statement Converter - PDF to Excel/CSV Free | All Things Doc',
    seoDescription:
      'Convert PDF bank statements to Excel or CSV using AI. Extract transaction data from bank statements with privacy-focused no-login tool.',
    longDescription:
      'Transform PDF bank statements into structured Excel or CSV files using AI-powered data extraction. Our intelligent tool understands bank statement formats and accurately extracts transaction data, dates, amounts, and descriptions. No login required - completely private and secure for your financial data.',
  },
  [ToolID.GENERIC_TO_PDF]: {
    id: ToolID.GENERIC_TO_PDF,
    title: 'Convert to PDF',
    description: 'Turn almost any file (Doc, Images, etc) into a PDF.',
    icon: FilePlus,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['convert to pdf', 'file to pdf', 'create pdf'],
  },
  [ToolID.WORD_TO_PDF]: {
    id: ToolID.WORD_TO_PDF,
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting to PDF.',
    icon: FileType2,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['word to pdf', 'docx to pdf'],
  },
  [ToolID.POWERPOINT_TO_PDF]: {
    id: ToolID.POWERPOINT_TO_PDF,
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view as PDF.',
    icon: Presentation,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['ppt to pdf', 'powerpoint to pdf'],
  },
  [ToolID.EXCEL_TO_PDF]: {
    id: ToolID.EXCEL_TO_PDF,
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting to PDF.',
    icon: FileSpreadsheet,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['excel to pdf', 'xls to pdf'],
  },
  [ToolID.JPG_TO_PDF]: {
    id: ToolID.JPG_TO_PDF,
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    icon: ImageIcon,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['jpg to pdf', 'image to pdf', 'convert photo to pdf'],
  },
  [ToolID.HTML_TO_PDF]: {
    id: ToolID.HTML_TO_PDF,
    title: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF.',
    icon: Globe,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['html to pdf', 'webpage to pdf', 'url to pdf'],
  },
  [ToolID.PDF_TO_JPG]: {
    id: ToolID.PDF_TO_JPG,
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.PDF_TOOLS,
    keywords: ['pdf to jpg', 'pdf to image'],
  },
  [ToolID.PDF_TO_PNG]: {
    id: ToolID.PDF_TO_PNG,
    title: 'PDF to PNG',
    description: 'Convert PDFs to PNG or other image formats.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.PDF_TOOLS,
  },
  [ToolID.PDF_TO_PDFA]: {
    id: ToolID.PDF_TO_PDFA,
    title: 'PDF to PDF/A',
    description: 'Transform your PDF to ISO-standardized PDF/A for archiving.',
    icon: FileArchive,
    color: 'text-amber-700',
    bgColor: 'bg-amber-100',
    category: ToolCategory.PDF_TOOLS,
  },

  // --- OFFICE TOOLS ---
  [ToolID.WORD_TO_EXCEL]: {
    id: ToolID.WORD_TO_EXCEL,
    title: 'Word to Excel',
    description: 'Convert data tables from Word documents to Excel sheets.',
    icon: FileSpreadsheet,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_WORD]: {
    id: ToolID.EXCEL_TO_WORD,
    title: 'Excel to Word',
    description: 'Convert spreadsheets into formatted Word documents.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.PPT_TO_WORD]: {
    id: ToolID.PPT_TO_WORD,
    title: 'PPT to Word',
    description: 'Convert PowerPoint slides into a Word document.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_PPT]: {
    id: ToolID.WORD_TO_PPT,
    title: 'Word to PowerPoint',
    description: 'Convert Word documents into a PowerPoint presentation.',
    icon: Presentation,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_CSV]: {
    id: ToolID.EXCEL_TO_CSV,
    title: 'Excel to CSV',
    description: 'Convert Excel spreadsheets to CSV format.',
    icon: FileSpreadsheet,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.CSV_TO_EXCEL]: {
    id: ToolID.CSV_TO_EXCEL,
    title: 'CSV to Excel',
    description: 'Convert CSV files into Excel spreadsheets.',
    icon: Table,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.TEXT_TO_WORD]: {
    id: ToolID.TEXT_TO_WORD,
    title: 'Text to Word',
    description: 'Convert plain text files into Word documents.',
    icon: FileType2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_TEXT]: {
    id: ToolID.WORD_TO_TEXT,
    title: 'Word to Text',
    description: 'Extract plain text from Word documents.',
    icon: FileText,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.WORD_TO_JPG]: {
    id: ToolID.WORD_TO_JPG,
    title: 'Word to JPG',
    description: 'Convert Word document pages into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.PPT_TO_JPG]: {
    id: ToolID.PPT_TO_JPG,
    title: 'PPT to JPG',
    description: 'Convert PowerPoint slides into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.EXCEL_TO_JPG]: {
    id: ToolID.EXCEL_TO_JPG,
    title: 'Excel to JPG',
    description: 'Convert Excel spreadsheets into JPG images.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    category: ToolCategory.OFFICE_TOOLS,
  },
  [ToolID.MERGE_WORD]: {
    id: ToolID.MERGE_WORD,
    title: 'Merge Word',
    description: 'Combine multiple Word documents into one.',
    icon: Files,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['merge word documents', 'combine docx'],
  },
  [ToolID.COMPRESS_WORD]: {
    id: ToolID.COMPRESS_WORD,
    title: 'Compress Word',
    description: 'Reduce the file size of Word documents.',
    icon: Minimize2,
    color: 'text-blue-700',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress word', 'reduce docx size', 'shrink word document'],
  },
  [ToolID.COMPRESS_EXCEL]: {
    id: ToolID.COMPRESS_EXCEL,
    title: 'Compress Excel',
    description: 'Reduce the file size of Excel spreadsheets.',
    icon: Minimize2,
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress excel', 'reduce xlsx size', 'shrink excel file'],
  },
  [ToolID.COMPRESS_PPT]: {
    id: ToolID.COMPRESS_PPT,
    title: 'Compress PowerPoint',
    description: 'Reduce the file size of PowerPoint presentations.',
    icon: Minimize2,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['compress powerpoint', 'reduce ppt size', 'shrink presentation'],
  },

  // --- DEVELOPER TOOLS ---
  [ToolID.JSON_TO_CSV]: {
    id: ToolID.JSON_TO_CSV,
    title: 'JSON to CSV',
    description: 'Convert JSON data structures to CSV format.',
    icon: Database,
    color: 'text-cyan-700',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['json to csv', 'convert json'],
  },
  [ToolID.CSV_TO_JSON]: {
    id: ToolID.CSV_TO_JSON,
    title: 'CSV to JSON',
    description: 'Convert CSV spreadsheet data into JSON.',
    icon: FileJson,
    color: 'text-cyan-700',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },
  [ToolID.XML_TO_JSON]: {
    id: ToolID.XML_TO_JSON,
    title: 'XML to JSON',
    description: 'Convert XML data to JSON objects.',
    icon: FileCode,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },
  [ToolID.JSON_FORMATTER]: {
    id: ToolID.JSON_FORMATTER,
    title: 'JSON Formatter',
    description: 'Prettify, validate and minify JSON data structures.',
    icon: FileJson,
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['json prettifier', 'format json', 'json validator', 'minify json'],
  },
  [ToolID.WEB_FORMATTER]: {
    id: ToolID.WEB_FORMATTER,
    title: 'HTML/CSS Formatter',
    description: 'Prettify and indent messy HTML or CSS code for better readability.',
    icon: FileCode,
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['html prettifier', 'format css', 'code beautifier', 'indentation'],
  },
  [ToolID.PRIVACY_REDACTOR]: {
    id: ToolID.PRIVACY_REDACTOR,
    title: 'Privacy Redactor',
    description: 'Protect your sensitive data by automatically redacting emails, phones, and credit card numbers.',
    icon: Shield,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['pii redact', 'data privacy', 'hide sensitive info', 'anonymizer'],
  },
  [ToolID.EXIF_VIEWER]: {
    id: ToolID.EXIF_VIEWER,
    title: 'EXIF Viewer',
    description: 'Inspect detailed camera metadata, GPS location, and technical info embedded in photos.',
    icon: Tag,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['image metadata', 'photo info', 'gps coordinates', 'camera details'],
  },
  [ToolID.SIGNATURE_GENERATOR]: {
    id: ToolID.SIGNATURE_GENERATOR,
    title: 'Signature Pad',
    description: 'Create a digital electronic signature with your mouse or touch screen for documents.',
    icon: PenTool,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['e-signature', 'draw signature', 'digital sign', 'png signature'],
  },
  [ToolID.BASE64_ENCODER]: {
    id: ToolID.BASE64_ENCODER,
    title: 'Base64 Tool',
    description: 'Encode and decode text to and from Base64 format.',
    icon: ArrowRightLeft,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['base64 encode', 'base64 decode', 'text to base64'],
  },
  [ToolID.HASH_GENERATOR]: {
    id: ToolID.HASH_GENERATOR,
    title: 'Hash Generator',
    description: 'Generate secure SHA-256 and SHA-512 hashes for any text.',
    icon: Hash,
    color: 'text-red-600',
    bgColor: 'bg-red-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['sha256 generator', 'hash text', 'secure hash'],
  },
  [ToolID.UNIT_CONVERTER]: {
    id: ToolID.UNIT_CONVERTER,
    title: 'Unit Converter',
    description: 'Quickly convert between different units of measurement.',
    icon: RefreshCw,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['convert units', 'metric to imperial', 'temperature converter', 'area', 'volume', 'pressure'],
  },
  [ToolID.TEXT_CLEANER]: {
    id: ToolID.TEXT_CLEANER,
    title: 'Text Cleaner',
    description: 'Remove extra spaces, empty lines, and fix messy text formatting.',
    icon: Eraser,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['clean text', 'fix spaces', 'remove lines', 'smart quotes'],
  },
  [ToolID.IMAGE_TO_BASE64]: {
    id: ToolID.IMAGE_TO_BASE64,
    title: 'Image to Base64',
    description: 'Convert any image file into a Base64 Data URI string.',
    icon: Code,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['image to base64', 'data uri', 'base64 converter'],
  },
  [ToolID.LINE_UTILS]: {
    id: ToolID.LINE_UTILS,
    title: 'Line Utils',
    description: 'Sort lines, remove duplicates, and reverse text lists.',
    icon: AlignLeft,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['sort lines', 'remove duplicate lines', 'alphabetize', 'reverse list'],
  },
  [ToolID.URL_ENCODER]: {
    id: ToolID.URL_ENCODER,
    title: 'URL Encoder',
    description: 'Encode or decode URLs and parameters for safe web use.',
    icon: Link,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['url encode', 'url decode', 'percent encoding'],
  },
  [ToolID.CSV_EDITOR]: {
    id: ToolID.CSV_EDITOR,
    title: 'CSV Editor',
    description: 'Upload, view, and edit CSV files directly in your browser.',
    icon: Table,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['csv editor', 'view csv', 'edit spreadsheet', 'online csv'],
  },
  [ToolID.DATE_CALCULATOR]: {
    id: ToolID.DATE_CALCULATOR,
    title: 'Date Calculator',
    description: 'Calculate days between dates, add/subtract time, and convert timezones.',
    icon: RefreshCw,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['date calculator', 'days between', 'timezone converter', 'time math'],
  },
  [ToolID.PERCENTAGE_CALCULATOR]: {
    id: ToolID.PERCENTAGE_CALCULATOR,
    title: 'Percentage Calculator',
    description: 'Calculate discounts, tips, percentage increases, and more.',
    icon: Hash,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['percentage calculator', 'discount calculator', 'tip calculator', 'percent off'],
  },
  [ToolID.LOAN_CALCULATOR]: {
    id: ToolID.LOAN_CALCULATOR,
    title: 'Loan Calculator',
    description: 'Calculate monthly payments and total interest for mortgages or loans.',
    icon: Landmark,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['mortgage calculator', 'loan payment', 'interest calculator', 'finance'],
  },
  [ToolID.BMI_CALCULATOR]: {
    id: ToolID.BMI_CALCULATOR,
    title: 'BMI Calculator',
    description: 'Calculate your Body Mass Index (BMI) using metric or imperial units.',
    icon: Activity,
    color: 'text-rose-600',
    bgColor: 'bg-rose-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['bmi calculator', 'health calculator', 'body mass index', 'weight check'],
  },
  [ToolID.COLOR_CONVERTER]: {
    id: ToolID.COLOR_CONVERTER,
    title: 'Color Converter',
    description: 'Convert between HEX, RGB, and HSL color formats with a visual picker.',
    icon: Palette,
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['hex to rgb', 'color picker', 'color code', 'hsl converter'],
  },
  [ToolID.COLOR_CONTRAST_CHECKER]: {
    id: ToolID.COLOR_CONTRAST_CHECKER,
    title: 'Contrast Checker',
    description: 'Verify color combinations meet WCAG accessibility standards for readability.',
    icon: CheckCircle2,
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['contrast ratio', 'wcag check', 'accessibility tool', 'color pass'],
  },
  [ToolID.SCREEN_RECORDER]: {
    id: ToolID.SCREEN_RECORDER,
    title: 'Screen Recorder',
    description: 'Record your screen or specific windows directly in the browser with audio.',
    icon: Monitor,
    color: 'text-rose-600',
    bgColor: 'bg-rose-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['capture screen', 'video recording', 'browser recorder', 'screencast'],
  },
  [ToolID.QR_SCANNER]: {
    id: ToolID.QR_SCANNER,
    title: 'QR Code Scanner',
    description: 'Scan and decode QR codes using your camera or by uploading an image.',
    icon: Scan,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['qr reader', 'scan qr code', 'decode barcode', 'online qr scanner'],
  },
  [ToolID.STOPWATCH]: {
    id: ToolID.STOPWATCH,
    title: 'Stopwatch & Timer',
    description: 'Track time accurately with stopwatch, countdown timer, and lap records.',
    icon: Clock,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['stopwatch', 'timer', 'countdown', 'online clock'],
  },
  [ToolID.RANDOM_GENERATOR]: {
    id: ToolID.RANDOM_GENERATOR,
    title: 'Random Generator',
    description: 'Generate random numbers, pick winners from lists, or flip a virtual coin.',
    icon: RefreshCw,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['random number', 'pick random', 'dice roller', 'coin flip'],
  },
  [ToolID.ASPECT_RATIO_CALCULATOR]: {
    id: ToolID.ASPECT_RATIO_CALCULATOR,
    title: 'Aspect Ratio Calc',
    description: 'Calculate image and video aspect ratios, resolution scales, and common presets.',
    icon: Maximize,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['aspect ratio', 'resolution', 'image scale', 'video ratio'],
  },
  [ToolID.UNIX_TIMESTAMP_CONVERTER]: {
    id: ToolID.UNIX_TIMESTAMP_CONVERTER,
    title: 'Unix Timestamp',
    description: 'Convert Unix timestamps to human-readable dates and vice-versa.',
    icon: Clock,
    color: 'text-doc-slate',
    bgColor: 'bg-slate-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['unix time', 'epoch converter', 'timestamp', 'date to unix'],
  },
  [ToolID.NUMBER_TO_WORDS]: {
    id: ToolID.NUMBER_TO_WORDS,
    title: 'Number to Words',
    description: 'Convert numbers into written words for checks, legal documents, or accessibility.',
    icon: Type,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['number to text', 'spell out numbers', 'check writer', 'words to numbers'],
  },
  [ToolID.MORSE_CODE_CONVERTER]: {
    id: ToolID.MORSE_CODE_CONVERTER,
    title: 'Morse Code',
    description: 'Convert text to Morse code and listen to the audio signal.',
    icon: Radio,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['morse code', 'text to morse', 'telegraph', 'signal'],
  },
  [ToolID.STRING_ESCAPER]: {
    id: ToolID.STRING_ESCAPER,
    title: 'String Escaper',
    description: 'Escape or unescape HTML entities, JSON strings, and JavaScript characters.',
    icon: Code,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['html escape', 'json unescape', 'string literal', 'web entities'],
  },
  [ToolID.BASE64_TO_IMAGE]: {
    id: ToolID.BASE64_TO_IMAGE,
    title: 'Base64 to Image',
    description: 'Decode Base64 Data URI strings back into viewable and downloadable images.',
    icon: ImageIcon,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['base64 decode', 'data uri to image', 'base64 viewer'],
  },
  [ToolID.TEXT_CASE_CONVERTER]: {
    id: ToolID.TEXT_CASE_CONVERTER,
    title: 'Text Case Converter',
    description: 'Transform text between UPPERCASE, lowercase, Title Case, and more.',
    icon: Type,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['text converter', 'uppercase to lowercase', 'title case'],
  },
  [ToolID.PASSWORD_GENERATOR]: {
    id: ToolID.PASSWORD_GENERATOR,
    title: 'Password Generator',
    description: 'Generate secure, random passwords with customizable criteria.',
    icon: RefreshCw,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['password generator', 'secure password', 'random string'],
  },
  [ToolID.PASSWORD_STRENGTH_CHECKER]: {
    id: ToolID.PASSWORD_STRENGTH_CHECKER,
    title: 'Password Strength',
    description: 'Check if your password is secure and how long it would take to crack.',
    icon: Shield,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['password check', 'is my password safe', 'password entropy', 'security'],
  },
  [ToolID.LOREM_IPSUM_GENERATOR]: {
    id: ToolID.LOREM_IPSUM_GENERATOR,
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for your designs and mockups.',
    icon: FileText,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text'],
  },
  [ToolID.WORD_COUNTER]: {
    id: ToolID.WORD_COUNTER,
    title: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in real-time.',
    icon: AlignLeft,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['word count', 'character count', 'writing stats'],
  },
  [ToolID.IMAGE_RESIZER]: {
    id: ToolID.IMAGE_RESIZER,
    title: 'Image Resizer',
    description: 'Change image dimensions while maintaining quality.',
    icon: Maximize,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['resize image', 'image dimensions', 'scale photo'],
  },
  [ToolID.IMAGE_CROPPER]: {
    id: ToolID.IMAGE_CROPPER,
    title: 'Image Cropper',
    description: 'Crop images to your desired aspect ratio and size.',
    icon: Crop,
    color: 'text-rose-600',
    bgColor: 'bg-rose-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['crop image', 'image editor', 'trim photo'],
  },
  [ToolID.IMAGE_COMPRESSOR]: {
    id: ToolID.IMAGE_COMPRESSOR,
    title: 'Image Compressor',
    description: 'Reduce image file size while maintaining visual quality.',
    icon: Minimize2,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['compress image', 'reduce photo size', 'optimize image'],
  },
  [ToolID.MARKDOWN_TOOL]: {
    id: ToolID.MARKDOWN_TOOL,
    title: 'Markdown Editor',
    description: 'Write and preview Markdown with GitHub-flavored styling.',
    icon: FileText,
    color: 'text-doc-slate',
    bgColor: 'bg-slate-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['markdown editor', 'md preview', 'writing tool'],
  },
  [ToolID.DIFF_CHECKER]: {
    id: ToolID.DIFF_CHECKER,
    title: 'Diff Checker',
    description: 'Compare two text snippets and see the differences.',
    icon: GitCompare,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['text compare', 'diff tool', 'code diff'],
  },
  [ToolID.EXIF_REMOVER]: {
    id: ToolID.EXIF_REMOVER,
    title: 'EXIF Remover',
    description: 'Strip sensitive metadata from JPEG images for privacy.',
    icon: Shield,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['strip exif', 'remove metadata', 'image privacy'],
  },
  [ToolID.JSON_TO_TYPESCRIPT]: {
    id: ToolID.JSON_TO_TYPESCRIPT,
    title: 'JSON to TS',
    description: 'Generate TypeScript interfaces from JSON objects.',
    icon: Code,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['json to typescript', 'interface generator', 'dev tool'],
  },
  [ToolID.SQL_FORMATTER]: {
    id: ToolID.SQL_FORMATTER,
    title: 'SQL Formatter',
    description: 'Prettify and format SQL queries for multiple dialects.',
    icon: Database,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['sql prettifier', 'format sql', 'db tool'],
  },
  [ToolID.SVG_CONVERTER]: {
    id: ToolID.SVG_CONVERTER,
    title: 'SVG to PNG',
    description: 'Convert SVG vectors to high-resolution PNG images.',
    icon: ImageIcon,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['svg to png', 'vector converter', 'export svg'],
  },
  [ToolID.COLOR_PALETTE]: {
    id: ToolID.COLOR_PALETTE,
    title: 'Color Palette',
    description: 'Extract dominant color palettes from any image.',
    icon: Palette,
    color: 'text-rose-600',
    bgColor: 'bg-rose-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['extract color', 'image palette', 'color scheme'],
  },
  [ToolID.REGEX_TESTER]: {
    id: ToolID.REGEX_TESTER,
    title: 'Regex Tester',
    description: 'Test and debug regular expressions in real-time.',
    icon: Search,
    color: 'text-slate-700',
    bgColor: 'bg-slate-200',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['regex tester', 'regular expression', 'regex debug'],
  },
  [ToolID.YAML_TO_JSON]: {
    id: ToolID.YAML_TO_JSON,
    title: 'YAML to JSON',
    description: 'Convert YAML configuration files into JSON format.',
    icon: FileCode,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['yaml to json', 'convert yaml', 'config converter'],
  },
  [ToolID.HTML_TO_MARKDOWN]: {
    id: ToolID.HTML_TO_MARKDOWN,
    title: 'HTML to MD',
    description: 'Convert HTML code or snippets into clean Markdown.',
    icon: Code,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.OFFICE_TOOLS,
    keywords: ['html to markdown', 'convert html to md'],
  },
  [ToolID.JSON_TO_YAML]: {
    id: ToolID.JSON_TO_YAML,
    title: 'JSON to YAML',
    description: 'Convert JSON data objects into YAML format.',
    icon: FileCode,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['json to yaml', 'convert json', 'yaml export'],
  },
  [ToolID.SPEECH_TO_TEXT]: {
    id: ToolID.SPEECH_TO_TEXT,
    title: 'Voice Transcriber',
    description: 'Convert your voice into text in real-time on your device.',
    icon: Mic,
    color: 'text-doc-red',
    bgColor: 'bg-red-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['speech to text', 'voice typing', 'dictation'],
  },
  [ToolID.JSON_TO_XML]: {
    id: ToolID.JSON_TO_XML,
    title: 'JSON to XML',
    description: 'Convert JSON objects to XML format.',
    icon: FileCode,
    color: 'text-orange-700',
    bgColor: 'bg-orange-100',
    category: ToolCategory.DEVELOPER_TOOLS,
  },
  [ToolID.JWT_SECRET_GENERATOR]: {
    id: ToolID.JWT_SECRET_GENERATOR,
    title: 'JWT Secret Generator',
    description: 'Generate secure random secrets for JWT token signing.',
    icon: KeyIcon,
    color: 'text-purple-700',
    bgColor: 'bg-purple-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['jwt secret', 'token generator', 'jwt signing', 'secret key', 'authentication'],
  },
  [ToolID.UUID_GENERATOR]: {
    id: ToolID.UUID_GENERATOR,
    title: 'UUID Generator',
    description: 'Generate random Version 4 UUIDs instantly.',
    icon: Hash,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['uuid generator', 'guid generator', 'v4 uuid', 'random id', 'unique identifier'],
  },

  // --- IMAGE & AUDIO ---
  [ToolID.TEXT_TO_SPEECH]: {
    id: ToolID.TEXT_TO_SPEECH,
    title: 'Text to Speech',
    description: 'Convert written text into natural-sounding speech.',
    icon: Mic,
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['text to speech', 'free tts', 'read text aloud'],
  },
  [ToolID.IMAGE_CONVERTER]: {
    id: ToolID.IMAGE_CONVERTER,
    title: 'Image Converter',
    description: 'Convert images to JPG, PNG, or WEBP instantly.',
    icon: FileType,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['image converter', 'jpg to png', 'png to jpg', 'webp converter'],
  },
  [ToolID.QR_GENERATOR]: {
    id: ToolID.QR_GENERATOR,
    title: 'QR Code Generator',
    description: 'Create customizable QR codes for URLs, text, and more.',
    icon: QrCode,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.MEDIA_TOOLS,
    keywords: ['qr code', 'generate qr', 'barcode'],
  },
  [ToolID.FILE_HASHER]: {
    id: ToolID.FILE_HASHER,
    title: 'File Checksum',
    description: 'Calculate secure SHA-256 and SHA-512 hashes for any file locally.',
    icon: Hash,
    color: 'text-rose-600',
    bgColor: 'bg-rose-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['file hash', 'checksum', 'sha256', 'file integrity'],
  },
  [ToolID.JWT_DECODER]: {
    id: ToolID.JWT_DECODER,
    title: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) header and payload.',
    icon: KeyIcon,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
    category: ToolCategory.DEVELOPER_TOOLS,
    keywords: ['jwt', 'decode jwt', 'token inspector'],
  },
};

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Chinese (Simplified)',
  'Japanese',
  'Korean',
  'Russian',
  'Portuguese',
  'Italian',
  'Dutch',
];

export const CODING_LANGUAGES = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Go',
  'Rust',
  'Swift',
  'PHP',
];
